name: Update Upstream Source

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source
      uses: actions/checkout@v1
      with:
        ref: ${{ github.ref }}

    - name: print info
      run: |
        echo ${{ github.ref }}
        echo ${{ github.workflow }}
        echo ${{ github.run_id }}
        echo ${{ github.action }}
        echo ${{ github.actions }}
        echo ${{ github.actor }}
        echo ${{ github.repository }}
        echo ${{ github.event_name }}
        echo ${{ github.event_path }}
        
      


