name: Update Upstream Source

on:
  push:                                                                             branches:                                                                         - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source
      uses: actions/checkout@v1
      with:
        ref: ${{ github.ref }}

    - name: print info
      run: |
        echo ${{ github.ref }}


