name: Update Upstream Source

on:
  push:
    branches: 
      - 'source-*'
jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      UPSTREAM_NAME: upstream

    steps:
    - name: Checkout Source
      uses: actions/checkout@v1
      with:
        ref: ${{ github.ref }} 
    
    - name: set upstream source
      if: contains( github.ref, 'lean' )
      env:
        UPSTREAM_URL: 'https://github.com/coolsnowwolf/lede.git' 
      run: |
        git remote add $UPSTREAM_NAME $UPSTREAM_URL
        
    - name: set lean upstream source
      if: contains( github.ref , 'lienol' )
      env:
        UPSTREAM_URL: 'https://github.com/Lienol/lean-lede.git' 
      run: |
        git remote add $UPSTREAM_NAME $UPSTREAM_URL   
        
    - name: print info
      run: |
        echo ${{ github.ref }}
        echo ${{ github.workflow }}
        echo ${{ github.run_id }}
        echo ${{ github.action }}
        echo ${{ github.actions }}
        echo ${{ github.actor }}
        echo ${{ github.repository }}
        echo ${{ github.event_name }}
        echo ${{ github.event_path }}
        
      


